Vagrant.configure("2") do |config|
  config.vm.box = "windows10-zhcn"
  config.vm.define "win10-dev"
  config.vm.boot_timeout = 300
  
  config.vm.network "forwarded_port", guest: 3389, host: 53389, auto_correct: true
  config.vm.network "forwarded_port", guest: 5985, host: 55985, auto_correct: true
  config.vm.network "forwarded_port", guest: 5986, host: 55986, auto_correct: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8192
    vb.cpus = 2
    vb.gui = true
    vb.name = "Win10-Dev"
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    vb.customize ["modifyvm", :id, "--vram", 256]
  end

  config.vm.communicator = "winrm"
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.winrm.timeout = 300
end
